image: "imrehg/archlinux-makepkg"

before_script:
- sudo pacman -Syu --noconfirm

package:
  script:
  - makepkg -s --noconfirm
  artifacts:
    paths:
    - pkg/
    - r-expm-*.tar.xz
    expire_in: 2 days


